apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-secrets
  namespace: demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: SLACK_WEBHOOK
      remoteRef: { key: /kubernettes/platform/slackWebhook }
    - secretKey: DATABASE_URL
      remoteRef: { key: /kubernettes/sample/databaseUrl }
