apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: {{ include "sample-service.fullname" . }} }
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sample-service.name" . }}
