apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-service.fullname" . }}
  labels:
    {{- include "sample-service.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app.kubernetes.io/name: {{ include "sample-service.name" . }}
